POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "ford",
    "model": "mustang",
    "year":  2013,
    "mileage": 30000,
    "long": 40,
    "lat": 45,
    "price": 40000
}
### Approve report
PATCH http://localhost:3000/reports/2
Content-Type: application/json

{
    "approved": true
}

### Get estimate for an existing vehicle
GET  http://localhost:3000/reports?make=ford&model=mustang&long=44&lat=44&year=1982&mileage=30000